# monitor=,preferred,auto,auto

# Notebook monitor
monitor = desc:AU Optronics 0x6DA8, preferred, auto, auto 
#$second_monitor = HDMI-A-1
$second_monitor = DP-5  

## BenQ monitor
# Horizontal:
monitor = desc:BNQ BenQ GW2470 77H01982SL0, 1920x1080, auto-right, auto

# Vertical:
# monitor = desc:BNQ BenQ GW2470 77H01982SL0, 1920x1080, auto-right, auto, transform, 1

## Asus monitor
monitor = desc:ASUSTek COMPUTER INC VG27A M3LMQS348505, preferred, auto-up, 1.666667 
