network={
        ssid="eduroam"
        key_mgmt=WPA-EAP
        pairwise=CCMP
        group=CCMP TKIP
        eap=PEAP
        ca_cert="/home/tomast/.config/cat_installer/ca.pem"
        identity="14893488"
        altsubject_match="DNS:radius1.eduroam.cuni.cz;DNS:radius2.eduroam.cuni.cz"
        phase2="auth=MSCHAPV2"
	password="tomsut"

}