require "install"
require	"options"
require "keymap"
require "colorscheme"
--require("lspconfig").setup()
require "keymaps"
require "colorscheme"
require "plugins"
require "lsp"
require "autocomplete"
